# Generated by Django 5.2.7 on 2025-11-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deli',
            fields=[
                ('deli_ID', models.AutoField(primary_key=True, serialize=False)),
                ('deli_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='deli_id',
        ),
        migrations.AddField(
            model_name='user',
            name='delis',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.deli'),
        ),
    ]
