# Generated by Django 5.2.7 on 2025-11-15 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_deli_remove_user_deli_id_user_delis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_checklists', to=settings.AUTH_USER_MODEL)),
                ('deli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='accounts.deli')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='accounts.checklisttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='accounts.checklist')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to=settings.AUTH_USER_MODEL)),
                ('deli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.deli')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('datetime', 'Date & Time'), ('decimal', 'Decimal Number'), ('number', 'Whole Number'), ('boolean', 'Yes/No')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='accounts.checklisttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_date', models.DateField(blank=True, null=True)),
                ('answer_datetime', models.DateTimeField(blank=True, null=True)),
                ('answer_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('answer_number', models.IntegerField(blank=True, null=True)),
                ('answer_boolean', models.BooleanField(blank=True, null=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='accounts.checklistitem')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.checklistresponse')),
                ('template_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='accounts.templatefield')),
            ],
        ),
    ]
