# Generated by Django 5.2.7 on 2025-11-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_checklisttemplate_checklist_checklistitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='checklist_date',
        ),
        migrations.AddField(
            model_name='checklist',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
    ]
