# Generated by Django 5.2.7 on 2025-11-19 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_checklist_checklist_date_checklist_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseitem',
            name='response',
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='accounts.checklist')),
                ('deli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.deli')),
            ],
            options={
                'unique_together': {('checklist', 'deli', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.checklistitem')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.checklistinstance')),
            ],
        ),
        migrations.DeleteModel(
            name='ChecklistResponse',
        ),
    ]
