# Generated by Django 5.2.7 on 2025-11-19 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_responseitem_response_checklistinstance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='accounts.checklist')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to=settings.AUTH_USER_MODEL)),
                ('deli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.deli')),
            ],
        ),
    ]
