# Generated by Django 5.2.7 on 2025-11-19 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_checklistresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseitem',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.checklistresponse'),
        ),
    ]
