# Generated by Django 5.2.7 on 2026-01-17 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_responseitem_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseitem',
            name='answer_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responseitem',
            name='response',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.checklistresponse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('decimal', 'Decimal Number'), ('number', 'Whole Number'), ('boolean', 'Yes/No')], max_length=20),
        ),
    ]
