# Generated by Django 5.2.7 on 2026-01-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_responseitem_answer_time_alter_responseitem_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
