# Generated by Django 5.2.7 on 2026-01-17 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_checklistresponse_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseitem',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responseitem',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_response_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
