# Generated by Django 5.2.7 on 2026-01-31 11:48

from django.db import migrations


def create_cleaning_record_template(apps, schema_editor):
    ChecklistTemplate = apps.get_model("accounts", "ChecklistTemplate")
    TemplateField = apps.get_model("accounts", "TemplateField")

    template, _ = ChecklistTemplate.objects.get_or_create(
        code="CLEANING_RECORD",
        defaults={
            "name": "Cleaning Record",
            "description": "Cleaning record checklist",
            "is_active": True,
        },
    )

    field_defs = [
        {
            "name": "chemical_used",
            "label": "Chemical Used",
            "field_type": "text",
            "required": False,
            "order": 1,
        },
        {
            "name": "actioned",
            "label": "Actioned",
            "field_type": "boolean",
            "required": True,
            "order": 2,
        },
        {
            "name": "deepclean",
            "label": "Deep Clean",
            "field_type": "boolean",
            "required": True,
            "order": 3,
        },
    ]

    for field_def in field_defs:
        TemplateField.objects.get_or_create(
            template=template,
            name=field_def["name"],
            defaults={
                "label": field_def["label"],
                "field_type": field_def["field_type"],
                "required": field_def["required"],
                "order": field_def["order"],
            },
        )


def remove_cleaning_record_template(apps, schema_editor):
    ChecklistTemplate = apps.get_model("accounts", "ChecklistTemplate")
    TemplateField = apps.get_model("accounts", "TemplateField")

    try:
        template = ChecklistTemplate.objects.get(code="CLEANING_RECORD")
    except ChecklistTemplate.DoesNotExist:
        return

    TemplateField.objects.filter(template=template).delete()
    template.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_responseitem_last_edited_at_and_more"),
    ]

    operations = [
        migrations.RunPython(create_cleaning_record_template, remove_cleaning_record_template),
    ]