# Generated by Django 5.2.7 on 2026-01-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_create_cleaning_record_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitem",
            name="chemical_used",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]